[auth]
allowed_redirect_urls = ["http://localhost:3000/api/auth/callback", "http://localhost:3000/login"]
require_email_verification = true
verify_email_method = "code"
reset_password_method = "code"

[auth.password]
min_length = 6
require_number = false
require_lowercase = false
require_uppercase = false
require_special_char = false
